### ISSUE TITLE
MaxEngine appears to create an input tensor per GPU during inference even when using PP or TP

### ISSUE THREAD

**Issue by gabeweisz** [AI-Hypercomputer/maxtext#1078]
If I look at [MaxEngine.max_concurrent_decodes](https://github.com/AI-Hypercomputer/maxtext/blob/6f36556bf4017c95493d6cc44900793e5d860b54/MaxText/maxengine.py#L573C5-L573C71) and [init_decode_state()](https://github.com/AI-Hypercomputer/maxtext/blob/6f36556bf4017c95493d6cc44900793e5d860b54/MaxText/maxengine.py#L519C10-L519C76), it appears that an input tensor per GPU is created even if TP or PP is configured. I also see that inference_microbenchmark uses MaxEngine.max_concurrent_decodes as the [global batch size](https://github.com/AI-Hypercomputer/maxtext/blob/6f36556bf4017c95493d6cc44900793e5d860b54/MaxText/inference_microbenchmark.py#L299C4-L299C41).
Is this intended, and does this mean that TP and PP don't work for inference right now?

**Comment by jwyang-google** [comment]
hi, the sharding is not handled when we declear the tensor. Sharding is handled by using the jax sharding module functions. For the input tensor you refered, the sharding is handled by these lines: https://github.com/AI-Hypercomputer/maxtext/blob/6f36556bf4017c95493d6cc44900793e5d860b54/MaxText/maxengine.py#L544-L558

**Comment by gabeweisz** [comment]
Thanks - why is global batch size = per_device_batch_size*num_devices when TP is configured in the config file? I am specifically referring to [this code](https://github.com/AI-Hypercomputer/maxtext/blob/6f36556bf4017c95493d6cc44900793e5d860b54/MaxText/inference_microbenchmark.py#L299C4-L299C41) that sets global batch size from engine.max_decodes.

**Comment by jwyang-google** [comment]
global batch size is always referred as the total batch size across all devices. It is not related to sharding in the config. In maxtext, sharding is handled in the engine and the layer (like attention & mlp) implementation.

**Comment by gabeweisz** [comment]
I see - so you would need to set a fractional per-device batch size if you want a global batch size that is not a multiple of GPUs
