### ISSUE TITLE
Cannot do inference in float32

### ISSUE THREAD

**Issue by borisdayma** [AI-Hypercomputer/maxtext#595]
If we try to perform inference in float32, we get the error:
```
AssertionError: Key and Value Dtypes should match
```

This error comes from [this line](https://github.com/google/maxtext/blob/ebd39aa64d670fa13a313b6f776e01ad9e450321/MaxText/layers/attentions.py#L513).

The origin of the error is that the cache `dtype` is set to `jnp.int8 if quantize_kvcache else jnp.bfloat16` but never to `jnp.float32`.

**Comment by rwitten** [comment]
What are you setting that triggets this? (Activations to float32?)

**Comment by borisdayma** [comment]
Yes it's the dtype: https://github.com/google/maxtext/blob/f52e6f7b49277688f68a58284d1ff7873122ca41/MaxText/configs/base.yml#L61

**Comment by bvandermoon** [comment]
Thanks @borisdayma for pointing this out. Created a [PR to address this](https://github.com/AI-Hypercomputer/maxtext/pull/936)

**Comment by bvandermoon** [comment]
Resolving this issue since the PR has been merged. Please reopen or let us know if you have any further issues

**Comment by borisdayma** [comment]
Thanks a lot for doing this @bvandermoon 🔥
