### ISSUE TITLE
https://us-python.pkg.dev/gce-ai-infra/maxtext-build-support-packages/simple/ not public

### ISSUE THREAD

**Issue by emergenz** [AI-Hypercomputer/maxtext#758]
I don't think https://us-python.pkg.dev/gce-ai-infra/maxtext-build-support-packages/simple/ is public.

**Comment by gobbleturk** [comment]
Does this cause issues for you during setup.sh?

**Comment by emergenz** [comment]
Yes, here: https://github.com/google/maxtext/blob/ef9a6e9b96aef039797ecfcd20dd9ec554f8e387/setup.sh#L106-L108

**Comment by chajath** [comment]
It is a public facing repo. Could you share the exact error message you are seeing, please?

**Comment by emergenz** [comment]
I'll try to do it if I find time but I am super busy these days and it's been some time since I used maxtext (and that was on a cluster I am not using any more)

**Comment by emergenz** [comment]
But I think the error message to be expected is clear: We don't have access to that link, thus we need to just use pypi instead

**Comment by emergenz** [comment]
fwiw that worked for me (iirc)
