### ISSUE TITLE
Standalone checkpoint write seems to have memory leak

### ISSUE THREAD

**Issue by bernardhan33** [AI-Hypercomputer/maxtext#831]
Attempting to run a standalone checkpointing workload using an 1T model (9.96TiB checkpoint size) on 512 n2-standard-32 nodes and observing that the memory usage slowly increases over time and eventually reported OOM after ~ 60 writes. Here's the memory consumption chart:

![6upQPjZZfRXHvQr](https://github.com/user-attachments/assets/bfb64806-b5c9-438d-a1d4-f56952f4b92c)

**Comment by gobbleturk** [comment]
Have you been working on this? I think your team is good to own / investigate this one

**Comment by bernardhan33** [comment]
Sorry for the late comment. Going to close this one out for now as we are not actively investigating this.
